CREATE DATABASE IF NOT EXISTS quiz_project;
USE quiz_project;

CREATE TABLE IF NOT EXISTS users(
uid INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(50) NOT NULL UNIQUE,
password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS quizes (
qid INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(200) NOT NULL,
user_id INT NOT NULL,
time_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(user_id)REFERENCES users(uid)
);

CREATE TABLE IF NOT EXISTS questions(
lid INT AUTO_INCREMENT PRIMARY KEY,
quiz_id INT NOT NULL,
q_text TEXT NOT NULL,
FOREIGN KEY(quiz_id) REFERENCES quizes(qid)
);

CREATE TABLE IF NOT EXISTS choices(
cid INT AUTO_INCREMENT PRIMARY KEY,
question_id INT NOT NULL,
c_text TEXT NOT NULL,
correct_ans BOOLEAN NOT NULL DEFAULT 0,
FOREIGN KEY(question_id) REFERENCES questions(lid)
);